### ISSUE TITLE
Teller Cashier Management: View Cashier

### ISSUE THREAD

**Issue by karantakalkar** [openMF/web-app#761] opened 2020-05-14 15:57 UTC
![Screenshot from 2020-05-14 21-19-35](https://user-images.githubusercontent.com/54709463/81956979-9e301c00-9629-11ea-9630-788bb0b40b4d.png)

https://demo.mifos.io/#/tellers/46/cashiers/25

**Comment by spider0061** [comment] 2020-05-20 03:58
duplicate of #757

**Comment by karantakalkar** [comment] 2020-05-20 04:45
They are different, I forgot to add 'list page' for 757.

**Comment by BLasan** [comment] 2020-05-21 07:59
@karantakalkar Can I work on this?

**Comment by karantakalkar** [comment] 2020-05-21 08:24
G ahead, please

**Closed** 2020-05-22 13:01 UTC
Labels: good first issue
