### ISSUE TITLE
Manage Offices: Create Office Screen 

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#147] opened 2018-07-24 19:04 UTC
**Goal:**

As an operations manager or system administrator I want to create new offices so that I can define my office hierarchy. 

This task requires implementing the same create office workflow located at https://demo.openmf.org/#/createoffice

Reference:
* User Manual on Managing Offices: https://mifosforge.jira.com/wiki/spaces/docs/pages/67141727/Manage+Offices
* API Docs on Offices: https://demo.openmf.org/api-docs/apiLive.htm#offices

See 

![screen shot 2018-07-24 at 11 59 42 am](https://user-images.githubusercontent.com/823454/43160269-8fbbd0ae-8f39-11e8-9b63-e75f0875111e.png)

**Comment by nirmalks** [comment] 2018-08-28 09:16
I have a couple of queries.

1. The POST request for https://demo.openmf.org/fineract-provider/api/v1/offices throws a 500 error.

Request
`{"parentId":1,"name":"latestofficeaug28","locale":"en","dateFormat":"dd MMMM yyyy","openingDate":"28 August 2018"}`

Response:
`{"timestamp":1535446435479,"status":500,"error":"Internal Server Error","exception":"org.springframework.orm.jpa.JpaSystemException","message":"The transaction has been rolled back.  See the nested exceptions for details on the errors that occurred.; nested exception is <openjpa-2.4.1-r422266:1730418 fatal general error> org.apache.openjpa.persistence.PersistenceException: The transaction has been rolled back.  See the nested exceptions for details on the errors that occurred.\nFailedObject: org.apache.fineract.notification.domain.Topic@60852fba"}`

I cannot get the actual reason for the error. Is something wrong with the request?

2. Can I work on this issue?

**Comment by abhaychawla** [comment] 2018-08-29 06:50
@nirmalks There is nothing wrong with your request. It looks like there is an internal issue with the server. While the issue is resolved, you can go ahead and create the user interface for the screen. Make sure you follow all the guidelines.

**Comment by nirmalks** [comment] 2018-08-29 07:10
@abhaychawla Thanks for the clarification. Should the web page design be same as in the screenshot. I see that in the web app that in most places, placeholders are used instead of labels.

**Comment by abhaychawla** [comment] 2018-08-29 07:16
Fetch the latest code from the repository and have a look at the accounting section. The placeholders have been updated with labels. The screen should be implemented in a similar way to: https://openmf.github.io/web-app/accounting/closing-entries/create

**Closed** 2019-12-30 21:33 UTC
Labels: gci 2019, good first issue, help wanted, refactor
