### ISSUE TITLE
Manage Funds : Add/Edit Funds

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#155] opened 2018-07-25 05:40 UTC
Goal:

As a System Administrator, I want  to add funds and edit existing funds as seen at, 
https://demo.openmf.org/#/managefunds/

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141736/Manage+Funds

https://demo.openmf.org/api-docs/apiLive.htm#funds

![manage funds](https://user-images.githubusercontent.com/23022667/43181532-55abe31e-8ffb-11e8-95be-d79ef8f384d0.png)

**Comment by pearlMat** [comment] 2020-03-06 15:27
I would like to work on this issue, Assign it to me please,

**Comment by abhaychawla** [comment] 2020-03-06 18:10
@spider0061 why have you worked on the issue without commenting on it first? Please follow the guidelines.

**Comment by abhaychawla** [comment] 2020-03-06 18:11
@pearlMat Welcome to the community!! As this issue already has an existing PR, please look for another issue to work on.

**Comment by spider0061** [comment] 2020-03-06 18:30
@abhaychawla Sir, actually first I made an issue 575 for view manage funds component which was closed as it was duplicate of this issue but I commented there. I forgot to comment here as both of the issues were same. It was my mistake and it won't happen again.

**Closed** 2020-06-22 10:40 UTC
Labels: gsoc 2020
