### ISSUE TITLE
Google CodeIn Task:  Support for PWA with workbox.js

### ISSUE THREAD

**Issue by giorgiozoppi** [openMF/web-app#488] opened 2019-12-01 12:33 UTC
Mifos-X needs PWA support. It can be achieved easily using workbox.js. This will makes on Devices (Desktop/Mobile)  the web app installable and we can improve caching.

**Comment by abhaychawla** [comment] 2019-12-01 18:24
@giorgiozoppi This is a duplicate of https://github.com/openMF/web-app/issues/367
Also, this is not suitable to do for GCI students. This would be really hard. The web app is in development right now, PWA is a matter of discussion once we reach a stage where web app has at least all of the functionalities of the community app.

I would request you to please contribute the web app first and understand before creating tasks for students in google code in.

**Closed by abhaychawla** 2019-12-01 18:24 UTC
