### ISSUE TITLE
Edit and Delete Data Table

### ISSUE THREAD

**Issue by BLasan** [openMF/web-app#654] opened 2020-03-06 15:26 UTC
Component for editing data table is needed as in 
https://demo.mifos.io/#/editdatatable/A01-Mpesa

Delete task should also be added as in
https://demo.mifos.io/#/viewdatatable/A01-Mpesa

![Screenshot from 2020-03-06 20-55-41](https://user-images.githubusercontent.com/43112139/76097007-f7a61a00-5fec-11ea-9199-41e060fa10de.png)

**Comment by BLasan** [comment] 2020-03-06 15:27
@abhaychawla  I'll work on this

**Comment by abhaychawla** [comment] 2020-03-06 18:12
@BLasan if you try to claim and work on multiple issues at once, your PRs won't be accepted. Please follow the guidelines and work on one issue at a time.

**Comment by abhaychawla** [comment] 2020-03-06 18:14
This is a duplicate of https://github.com/openMF/web-app/issues/171 and already has an existing PR. Please check for existing issues before creating a new one.

**Closed by abhaychawla** 2020-03-06 18:14 UTC
