### ISSUE TITLE
Paging does not work on several screens

### ISSUE THREAD

**Issue by peter-santa-dpc** [openMF/web-app#1865] opened 2023-09-13 09:25 UTC
## Description
Paging does not work on several screens.
Scope of this ticket:
- listing journal entries
- listing audit trail events

### Audit trails
Go to 
- Admin / System / Audit trails

Set page size less than the existing records.

### Journal entries
Go to 
- Accounting / Search Journal entries

Set page size less than the existing records.

## Expected Behaviour
Paging works.

## Actual Behaviour
Paging does not work. Arrows are grey.

## Settings
- Mifos X version: b6efd0e08a3bd3c00e44f75a91f5a552af37f6c0
- Browser used: Firefox, Safari, Chrome

## Screenshots, if any
<img width="1218" alt="image" src="https://github.com/openMF/web-app/assets/45198877/23a98427-62b1-4e82-b8d8-309836ee759d">

<img width="1219" alt="image" src="https://github.com/openMF/web-app/assets/45198877/e36d7b8b-6238-46e1-aaed-b453d42411af">

**Comment by jdailey** [comment] 2023-09-13 12:08
Needs a fix .

**Comment by adamsaghy** [comment] 2023-09-13 14:10
@josehernandezfintecheandomx Can you please take a look on this ticket?

**Comment by adamsaghy** [comment] 2023-09-14 08:57
Closing. The problem is not UI issue. It requires changes at backend side.

**Closed by adamsaghy** 2023-09-14 08:57 UTC

**Comment by peter-santa-dpc** [comment] 2023-11-16 10:55
Then https://issues.apache.org/jira/browse/FINERACT-2013 might solve the issues.
