### ISSUE TITLE
Manage Funds: Add Manage Funds Component

### ISSUE THREAD

**Issue by spider0061** [openMF/web-app#575] opened 2020-01-16 12:46 UTC
Admin should be able to see funds.This issue is related to #155 which is to add feature of add/edit manage funds. But before that there should be a component which can display funds

related image:
![43181532-55abe31e-8ffb-11e8-95be-d79ef8f384d0](https://user-images.githubusercontent.com/45865775/72526253-01808c00-388c-11ea-8b8f-daef9527ad82.png)

useful links:
https://mifosforge.jira.com/wiki/spaces/docs/pages/67141736/Manage+Funds
https://demo.openmf.org/api-docs/apiLive.htm#funds

**Comment by spider0061** [comment] 2020-01-16 12:48
@abhaychawla I would like to work on this.

**Comment by abhaychawla** [comment] 2020-01-27 20:26
@spider0061 Sorry for the late reply but this is not related to the issue rather a duplicate of the same unless you suggest an enhancement by which the design can be improved. The same component is being used to view/add/edit.

**Closed by abhaychawla** 2020-01-27 20:26 UTC

**Comment by spider0061** [comment] 2020-01-29 06:46
@abhaychawla  it's okay. Maybe I had something else in my mind at that time. I have created a PR for view funds component please review it and I'll add add/edit feature once it is reviewed.
