### ISSUE TITLE
Can't select Address Type from Drop-down menu

### ISSUE THREAD

**Issue by edcable** [openMF/web-app#1267] opened 2020-10-27 21:48 UTC
## Description
I was attempting to create a new client to see if the issue of not being able to add new street field was also present in the Web App https://github.com/openMF/community-app/pull/3250

Unfortunately I wasn't able to get far enough to test

## Steps to Reproduce
Attempt to create a client, enter general details, enter family members if needed, on the address step of the wizard, you can't select the address type from the drop-down (I confirmed that that there are two active address types from the manage code values section of this field. 
Please add as much detail as possible to reproduce the error/issue.
Don't assume the reader knows anything about the Mifos X Web App.
![Screenshot 2020-10-27 at 2 44 01 PM](https://user-images.githubusercontent.com/823454/97365748-69282680-1863-11eb-9662-d12d94448a38.png)

**Comment by karantakalkar** [comment] 2020-10-28 04:14
@edcable this is duplicate of #1229, due to minor change in response from backend on different servers, address options are avilable on one and unavailable on another.

**Comment by edcable** [comment] 2020-10-28 04:50
Sorry I didn't catch that. Which server should I access to test?

**Comment by karantakalkar** [comment] 2020-10-28 04:52
demo.midos.io

**Comment by edcable** [comment] 2020-11-12 13:33
I'm having issues testing this as the two instances that aren't pointing to staging.mifos.io have an older build so I can't actually create a client:

* https://webapp.mifos.io/
* https://wui.fineract.dev/

https://openmf.github.io/web-app/home has the latest web app codebase but since it's pointing to staging, I can't access the dropdowns.

**Comment by karantakalkar** [comment] 2020-11-12 13:55
We can change it for dev and staging, but it would stop working on demo.mifos.io then, a minor difference in API response on servers is causing this.

**Comment by edcable** [comment] 2020-11-12 14:05
@karantakalkar is it the case that this has been fixed on the back-end in later versions and that's why the issues is just on demo.mifos.io which is still on an old codebase and not the latest release.

**Comment by karantakalkar** [comment] 2020-11-12 14:10
Yes that could be the problem, when i was developing it I tested client creation on demo and shaped front end code to it its API response, should the code be modified for staging and dev then?

**Comment by edcable** [comment] 2020-11-12 14:30
I think yes it should be shaped to staging and dev code as that's the latest back-end code we'll move forward with.

**Comment by karantakalkar** [comment] 2020-11-17 11:10
tracking in #1229

**Closed by karantakalkar** 2020-11-17 11:10 UTC
Labels: bug, duplicate
