### ISSUE TITLE
Products: List - Loan, Savings, Shares, Fixed Deposit, Recurring Deposit, Floating Rates and charges

### ISSUE THREAD

**Issue by santoshconflux** [openMF/web-app#187] opened 2018-07-25 08:35 UTC
Goal:
As a system admin, I want to view product list, as seen at,
https://demo.openmf.org/#/loanproducts
https://demo.openmf.org/#/savingproducts
https://demo.openmf.org/#/shareproducts
https://demo.openmf.org/#/fixeddepositproducts
https://demo.openmf.org/#/recurringdepositproducts
https://demo.openmf.org/#/floatingrates
https://demo.openmf.org/#/charges
Example: Loan Product List:
![1_loanproductlist](https://user-images.githubusercontent.com/23022667/43189171-99b52328-9013-11e8-9630-fd8899b13760.png)

Resources:
https://mifosforge.jira.com/wiki/spaces/docs/pages/70910295/Products
https://demo.openmf.org/api-docs/apiLive.htm#loanproducts
https://demo.openmf.org/api-docs/apiLive.htm#savingsproducts
https://demo.openmf.org/api-docs/apiLive.htm#shareproducts
https://demo.openmf.org/api-docs/apiLive.htm#fixeddepositproducts
https://demo.openmf.org/api-docs/apiLive.htm#recurringdepositproducts
https://demo.openmf.org/api-docs/apiLive.htm#floatingrates
https://demo.openmf.org/api-docs/apiLive.htm#charges

**Comment by jonathanzhang53** [comment] 2018-12-08 18:42
@abhaychawla could you reopen this? This issue refers to multiple screens. :D

**Comment by abhaychawla** [comment] 2018-12-08 18:47
Don't mention close or fix (any such keyword) in your PR along with the issue id unless the issue is actually resolved. It automatically closed the issue as it was mentioned it in the description when I merged the PR.

**Comment by jonathanzhang53** [comment] 2018-12-08 18:48
@abhaychawla got it. Thanks, I will go and fix that PR.

**Comment by abhaychawla** [comment] 2018-12-08 18:52
I made sure your commit message didn't contain that when I merged it. Although it was mentioned in the description of the PR as well due to which this issue got closed. I have edited it so no worries now. Just keep this in mind for later.

**Comment by abhaychawla** [comment] 2019-07-01 17:04
Parent issue for:
#429

**Comment by karantakalkar** [comment] 2020-08-08 12:01
@muskankhedia can this be closed?

**Comment by muskankhedia** [comment] 2020-08-08 12:21
@karantakalkar Yes, we can.

**Closed** 2020-08-08 12:21 UTC
Labels: enhancement, gci 2018, gsoc 2019, help wanted, refactor, track
