### ISSUE TITLE
Edit button not working

### ISSUE THREAD

**Issue by HARSH-nith** [openMF/web-app#1469] opened 2022-07-14 05:30 UTC
## Description
Edit button in the manage survey section not working.

## Steps to Reproduce
-> login
->admin
->survey
-> manage survey 

## Expected Behaviour
Able to edit survey when edit button is pressed

## Screenshots, if any
![error in manage survey](https://user-images.githubusercontent.com/75531664/178906549-e2e72a14-4fd7-4255-a8a9-59d72b68ca8c.jpg)

**Comment by bharathcgowda** [comment] 2022-07-15 13:54
duplicate of the ticket https://github.com/openMF/web-app/issues/1323
Hence closing it

**Closed by bharathcgowda** 2022-07-15 13:54 UTC
